apiVersion: v1
kind: ServiceAccount
metadata:
  name: netshoot
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      serviceAccountName: netshoot
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
