apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bedrock-premium
  namespace: agentgateway-system
spec:
  parentRefs:
    - name: agw
      namespace: agentgateway-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /bedrock/premium
      backendRefs:
        - name: bedrock-premium
          group: enterpriseagentgateway.solo.io
          kind: EnterpriseAgentgatewayBackend
      timeouts:
        request: "120s"
