apiVersion: v1
kind: Service
metadata:
  name: mcp2-server
  namespace: mcp
spec:
  selector:
    app: mcp2-server
  ports:
    - port: 80
      targetPort: 3001
      appProtocol: agentgateway.dev/mcp
